# Generated by Django 3.1.7 on 2021-03-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('adId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=20, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='platform_parsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_code', models.BooleanField(max_length=1, verbose_name='0 - ad from sale platform; 1 - ad from buy platform')),
                ('markaId', models.IntegerField()),
                ('model', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('photo_link', models.CharField(max_length=255, null=True)),
                ('date_add', models.DateTimeField(verbose_name='Created at')),
                ('ad_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sale_avg_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markaId', models.IntegerField()),
                ('model', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('avg_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='User name')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
            ],
        ),
    ]
