# Generated by Django 3.1.7 on 2021-03-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210311_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_code', models.BooleanField(max_length=1, verbose_name='0 - ad from sale platform; 1 - ad from buy platform')),
                ('model', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('photo_link', models.CharField(max_length=255, null=True)),
                ('date_add', models.DateTimeField(verbose_name='Created at')),
                ('ad_link', models.CharField(max_length=255)),
                ('brandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_avg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('avg_price', models.IntegerField()),
                ('brandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.brands')),
            ],
        ),
        migrations.DeleteModel(
            name='marka',
        ),
        migrations.DeleteModel(
            name='platform_parsed',
        ),
        migrations.DeleteModel(
            name='sale_avg_prices',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.users'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='adId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.platform'),
        ),
    ]
