# Generated by Django 3.1.7 on 2021-04-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20210312_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='adId',
            new_name='platformId',
        ),
        migrations.AlterField(
            model_name='platform',
            name='ad_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='photo_link',
            field=models.URLField(null=True),
        ),
    ]
