# Generated by Django 3.1.7 on 2021-04-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20210414_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='brandId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandId', to='ads.brands'),
        ),
    ]
