# Generated by Django 3.1.7 on 2021-04-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20210415_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='brandId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.brands'),
        ),
    ]
