# Generated by Django 4.0 on 2021-04-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20210415_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='brandId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='ads.brands'),
        ),
    ]
