# Generated by Django 4.0 on 2021-04-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_platform_brandid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='brandId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.brands'),
        ),
    ]
