# Generated by Django 4.0 on 2021-04-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_platform_brandid'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='price_diff',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='platformId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.platform', verbose_name='ad'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.users', verbose_name='user'),
        ),
    ]
