# Generated by Django 4.0 on 2021-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_platform_price_diff_alter_favorites_platformid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='price_diff',
            field=models.IntegerField(default=0),
        ),
    ]
