# Generated by Django 4.0 on 2021-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_favorites_userid_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='photo_link',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
