# Generated by Django 4.0 on 2021-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_platform_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='photo_link',
            field=models.URLField(null=True),
        ),
    ]
