# Generated by Django 4.0 on 2021-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_platform_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_avg',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
