# Generated by Django 4.0 on 2021-06-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_alter_sale_avg_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='fuel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
