# Generated by Django 4.0 on 2021-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_platform_country_platform_fuel_platform_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_avg',
            name='fuel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
