# Generated by Django 4.0 on 2021-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_sale_avg_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale_avg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
